apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /'true'
spec:
  rules:
  - host: careflow.com
    http:
      paths:
      - path: /api/members
        pathType: Prefix
        backend:
          service:
            name: members-clusterip-srv
            port:
              number: 80
      - path: /api/t/trips # trips service endpoint t added because it doesn't like both same endpoint /api/members
        pathType: Prefix
        backend:
          service:
            name: trips-clusterip-srv
            port:
              number: 80