# nodeport service configuration for memberservice application
apiVersion: v1
kind: Service
metadata:
  name: membernpservice-srv
spec:
  type: NodePort
  selector:
    app: memberservice
  ports:
  - name: memberservice
    protocol: TCP
    port: 80 #Node Port exposed inside the cluster
    targetPort: 8080 # Service port to which traffic will be forwarded in the pod ‚Üê App listens on 8080 for .NET 8+
    # nodePort: 32403 # Port exposed on each Node to access the service from outside the cluster